# Generated by Django 4.0.5 on 2022-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_categorie_fait_service_temoignage_projet_imageprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
